# Workflow name
name: 'Screenshot UI test'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run Chromatic tests
        run: npx chromatic --exit-zero-on-changes
        env:
          # 👇 Set the CHROMATIC_PROJECT_TOKEN as an environment variable
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
