name: Linting, Testing, Building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: yarn install
      - name: Build production
        run: yarn run build:prod
      - name: Lint typescript
        run: yarn run lint:ts
      - name: Lint css
        run: yarn run lint:css
      - name: Test unit
        run: yarn run test:unit
